### ISSUE TITLE
--experimental-resolve-tsconfig-paths flag not working reliably with TypeScript path aliases in   seed files

### ISSUE THREAD

**Issue by benmar000** [kysely-org/kysely-ctl#203]
Hey kysely-ctl team,

I ran into an issue when upgrading from 0.11 to v0.13.

The following was generated from my debugging by Claude Code. I hope it helps!

----------------------------------------------------------------
 Issue Summary

  The --experimental-resolve-tsconfig-paths flag introduced to resolve TypeScript path aliases is
  not working consistently, forcing users to use relative imports in seed files instead of clean
  path aliases.

  Environment

  - kysely-ctl version: 0.13.1
  - kysely version: 0.28.2
  - Node.js version: 22.11.0
  - TypeScript version: 5.7.2
  - OS: Linux (WSL2)

  Expected Behavior

  When using the --experimental-resolve-tsconfig-paths flag, TypeScript path aliases defined in
  tsconfig.json should be resolved correctly in seed files.

  Actual Behavior

  Despite using the flag, imports with TypeScript path aliases fail with module resolution errors,
   while the same imports work fine in the regular TypeScript compilation process.

  Steps to Reproduce

  1. Set up a project with TypeScript path aliases in tsconfig.json:
  {
    "compilerOptions": {
      "baseUrl": "./",
      "paths": {
        "@server/*": ["apps/server/*"]
      }
    }
  }

  2. Create a seed file using path aliases:
  import { createUserDto } from '@server/src/user/dto/create.user.dto';

  3. Run with experimental flag:
  kysely seed run --experimental-resolve-tsconfig-paths

  Error Output

  ERROR  Cannot find module '@server/src/user/dto/create.user.dto'
  Require stack:
  - /path/to/libs/kysely/seeds/seed_file.ts

  Debug Information

  When running with --debug, the output shows that jiti is successfully transpiling files when
  using relative imports, but fails to resolve path aliases even with the experimental flag
  enabled.

  Interestingly, running npx kysely seed run --experimental-resolve-tsconfig-paths --debug
  sometimes works, suggesting the flag may have timing or context issues when invoked through
  package managers or different execution contexts.

  Workaround

  Currently using relative imports instead of path aliases:
  // Instead of: import { dto } from '@server/src/user/dto/create.user.dto';
  import { dto } from '../../../apps/server/src/user/dto/create.user.dto';

  Additional Context

  This issue appears related to the v0.12.0 change from tsx to jiti for TypeScript file importing.
   While the --experimental-resolve-tsconfig-paths flag was added to address this, it doesn't seem
   to work reliably in all execution contexts.

  Request

  Could you investigate why the experimental flag isn't working consistently? It would be great to
   have reliable TypeScript path alias support since this is a common pattern in modern TypeScript
   projects.

**Comment by igalklebanov** [comment]
Hey 👋 

If your `tsconfig.json` file is exactly like the AI slopped here, I was able to reproduce your issue in the IDE, without even running `kysely-ctl` - it is coming from TypeScript paths misconfiguration.

Try the following:

```diff
    "paths": {
-      "@server/": ["apps/server/"]
+      "@server/*": ["apps/server/*"]
    },
```

If it doesn't solve your problem, Imma need a reproduction repository.
